<?xml version="1.0" encoding="utf-8"?><Database Name="Arcane_WebsiteMgt" Class="DemoModelEntitiesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=E:\cHashProject\Database\Arcane_WebsiteMgt.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="DbMethod.Properties.Settings" SettingsPropertyName="Arcane_WebsiteMgtConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LoginInfo" Member="LoginInfos">
    <Type Name="LoginInfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SmtpSettings" Member="SmtpSettings">
    <Type Name="SmtpSetting">
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SmtpServer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Port" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Websites" Member="Websites">
    <Type Name="Website">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MailTo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastCheckedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NextCheckAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CheckInterval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Website_Tag" Member="Tags" ThisKey="Id" OtherKey="WebsiteID" Type="Tag" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="WebsiteID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AttributeName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AttributeValue" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Website_Tag" Member="Website" ThisKey="WebsiteID" OtherKey="Id" Type="Website" IsForeignKey="true" />
    </Type>
  </Table>
</Database>